Added Autostart via GUI
ut-amrl/f1tenth_course pull request #22
Opened 2021-01-21 02:05 UTC by TongruiLi

Start VESC/LiDAR/Joystick/Websocket when GUI Icon is clicked.

2021-01-25 16:26 UTC, joydeep-b requested changes
1. The start button on the GUI calls the script that also tries to start the GUI (again).
2. Why do we need another start script?

2021-01-25 16:26 UTC, joydeep-b commented on src/gui/gui_mainwindow.cc
> +  Exec("roslaunch astra_camera astra.launch");
This calls the script that also starts the GUI

2021-01-25 16:26 UTC, joydeep-b commented on scripts/start_car_gui.sh
> +#!/bin/bash
Why do we need another start script?

2021-01-25 16:26 UTC, joydeep-b commented on gui/gui.desktop
> +[Desktop Entry]
This can go under `scripts`.

2021-02-01 18:21 UTC, TongruiLi commented on src/gui/gui_mainwindow.cc
> +  Exec("roslaunch ut_automata start_car.launch start_gui:=flase");
Need to fix typo.

2021-02-04 21:54 UTC, merged